plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.140'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {

            systemProperty 'forge.logging.markers', 'REGISTRIES'

            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    unitTest {
        enable()
        testedMod = mods.named("${mod_id}")
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // Testing dependencies
    testImplementation "org.junit.jupiter:junit-jupiter:${junit_version}"
    testImplementation "net.neoforged:testframework:${neo_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

dependencies {
    // SQLite and ORMLite
    jarJar(implementation("org.xerial:sqlite-jdbc:${sqlite_version}"))
    jarJar(implementation("com.j256:ormlite:${ormlite_version}"))
}

dependencies {
    def jarJarApiImpl = { String gav -> jarJar(api(implementation(gav))) }

    // Groovy
    jarJarApiImpl("org.apache.groovy:groovy:${groovy_version}")
}

dependencies {
    def jarJarApiImpl = { String gav -> jarJar(api(implementation(gav))) }

    jarJarApiImpl("org.lwjgl:lwjgl:${lwjgl_version}")
    jarJarApiImpl("org.lwjgl:lwjgl-meshoptimizer:${lwjgl_version}")
    jarJarApiImpl("org.lwjgl:lwjgl-opencl:${lwjgl_version}")
    jarJarApiImpl("org.lwjgl:lwjgl-par:${lwjgl_version}")
    jarJarApiImpl("org.lwjgl:lwjgl-shaderc:${lwjgl_version}")

    // Native platforms for LWJGL
    def lwjglNativePlatforms = ["natives-windows", "natives-linux", "natives-macos"]
    lwjglNativePlatforms.each { platform ->
        jarJar(runtimeOnly("org.lwjgl:lwjgl:${lwjgl_version}:${platform}"))
        jarJar(runtimeOnly("org.lwjgl:lwjgl-meshoptimizer:${lwjgl_version}:${platform}"))
        jarJar(runtimeOnly("org.lwjgl:lwjgl-par:${lwjgl_version}:${platform}"))
        jarJar(runtimeOnly("org.lwjgl:lwjgl-shaderc:${lwjgl_version}:${platform}"))
    }
}

dependencies {
    def jarJarApiImpl = { String dep -> jarJar(api(implementation(dep))) }

    // ImGui dependencies
    jarJarApiImpl("io.github.spair:imgui-java-binding:${imgui_version}")
    jarJar(api(implementation("io.github.spair:imgui-java-lwjgl3:${imgui_version}"))) {
        exclude group: "org.lwjgl"
        exclude group: 'org.lwjgl.lwjgl'
    }

    def imguiNativeArtifacts = ["imgui-java-natives-windows", "imgui-java-natives-linux", "imgui-java-natives-macos"]
    imguiNativeArtifacts.each { artifact ->
        jarJarApiImpl("io.github.spair:${artifact}:${imgui_version}")
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

test {
    useJUnitPlatform()
}

sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata

tasks.named("createMinecraftArtifacts") {
    dependsOn(generateModMetadata)
}

tasks.register('preCommit') {
    group = 'verification'
    description = 'Runs all things needed for a commit.'

    dependsOn tasks.named('check')
    dependsOn tasks.named('runData')
    dependsOn tasks.named('build')

    doLast {
        println "Done"
    }
}

tasks.register('copyExampleBundles', Copy) {
    group = 'foudryengine'
    description = 'Copys the Example Bundles to the run directory for testing.'

    from 'ExampleBundles'
    into 'run/FoundryEngine/bundles'
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = file("${projectDir}/repo").toURI()
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
