plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'org.jetbrains.dokka' version "2.1.0"
    id 'org.jetbrains.dokka-javadoc' version "2.1.0"
    id 'net.neoforged.moddev' version '2.0.140'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    mavenCentral()
    maven { url = "https://keksuccino.github.io/maven/" }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

test {
    useJUnitPlatform()
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

// Apply modular configuration files
apply from: 'gradle/neoforge.gradle'
apply from: 'gradle/publishing.gradle'
apply from: 'gradle/tasks.gradle'
apply from: 'dependencies.gradle'