dependencies {
    def bundle = { String gav -> jarJar(api(implementation(gav))) }

	//runtimeOnly "maven.modrinth:spark:${spark_version}"

	// Sodium
	compileOnly("maven.modrinth:AANobbMI:UETw0GTI")
	runtimeOnly("maven.modrinth:AANobbMI:UETw0GTI")

	// Iris
	compileOnly("maven.modrinth:YL57xq9U:BO8hxvMR")
	runtimeOnly("maven.modrinth:YL57xq9U:BO8hxvMR")

    // Testing dependencies
    testImplementation "org.junit.jupiter:junit-jupiter:${junit_version}"
    testImplementation "net.neoforged:testframework:${neo_version}"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    // CommonMark (Markdown) dependencies
    bundle "org.commonmark:commonmark:${commonmark_version}"
    bundle "org.commonmark:commonmark-ext-gfm-tables:${commonmark_version}"
    bundle "org.commonmark:commonmark-ext-gfm-strikethrough:${commonmark_version}"
    bundle "org.commonmark:commonmark-ext-autolink:${commonmark_version}"

    // Groovy
    bundle "org.apache.groovy:groovy:${groovy_version}"

	// JLayer
	bundle "com.googlecode.soundlibs:jlayer:${jlayer_version}"

	// JFLAC
	bundle "org.jflac:jflac-codec:${jflac_version}"

	// JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}")
    runtimeOnly("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // RenderDoc Support
    bundle "dev.latvian.mods:renderdoc-support:${renderdoc_support_version}"

	// Taffy (layout engine)
	bundle "dev.vfyjxf:taffy:${taffy_version}"

	// ImGui dependencies
    bundle "io.github.spair:imgui-java-binding:${imgui_version}"
    jarJar(api(implementation("io.github.spair:imgui-java-lwjgl3:${imgui_version}"))) {
        exclude group: "org.lwjgl"
        exclude group: 'org.lwjgl.lwjgl'
    }
    def imguiNativeArtifacts = ["imgui-java-natives-windows", "imgui-java-natives-linux", "imgui-java-natives-macos"]
    imguiNativeArtifacts.each { artifact ->
        bundle("io.github.spair:${artifact}:${imgui_version}")
    }
}