## Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Minecraft
minecraft_version=1.21.10
minecraft_version_range=[1.21.10,1.22)

## Neoforge
neo_version=21.10.64
neo_version_range=[21,)

## Loader
loader_version_range=[4,)

## Parchment
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

## Mod Properties
mod_id=toolboxlib
mod_name=ToolboxLib
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=io.github.luckymcdev
mod_authors=LuckyMcDev
mod_description=A Library.

## Library Versions
imgui_version=1.90.0
lwjgl_version=3.3.3
rendernurse_version=0.0.14