## Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)

## Neoforge
neo_version=26.1.2.31-beta
neo_version_range=[26.1.2, 26.2)

## Loader
loader_version_range=[4,)

## Mod Properties
mod_id=foundryengine
mod_name=Foundry Engine
mod_license=All Rights Reserved
mod_version=0.0.53
mod_group_id=de.luckymcdev
mod_authors=LuckyMcDev
mod_description=A Mod that tries to turn minecraft into a Game Engine.

## Library Versions
imgui_version=1.88.0
spark_version=1.10.172-neoforge
junit_version=5.7.1
groovy_version=5.0.4
commonmark_version=0.27.1
renderdoc_support_version=1.0.1-build.2
jei_version=29.5.0.28