modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "foundryengine"
version = "0.1.5"
displayName = "Foundry Engine"
authors = "LuckyMcDev"
description = "A Mod that tries to turn minecraft into a Game Engine."

[[mixins]]
config = "mixins/foundryengine.clock.mixins.json"

[[mixins]]
config = "mixins/foundryengine.command.mixins.json"

[[mixins]]
config = "mixins/foundryengine.input.mixins.json"

[[mixins]]
config = "mixins/foundryengine.level.mixins.json"

[[mixins]]
config = "mixins/foundryengine.mixins.json"

[[mixins]]
config = "mixins/foundryengine.render.mixins.json"

[[mixins]]
config = "mixins/foundryengine.screen.mixins.json"

[[mixins]]
config = "mixins/foundryengine.slot.mixins.json"

[[mixins]]
config = "mixins/foundryengine.sound.mixins.json"

[[mixins]]
config = "mixins/foundryengine.suggest.mixins.json"

[[mixins]]
config = "mixins/foundryengine.world.mixins.json"

[[dependencies."foundryengine"]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2.71,26.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies."foundryengine"]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.1,26.2)"
ordering = "NONE"
side = "BOTH"
