plugins {
    id 'net.neoforged.moddev' version '2.0.140' apply false
}

subprojects {
    apply plugin: 'groovy'
    apply plugin: 'java-library'
    apply plugin: 'net.neoforged.moddev'

    java.toolchain.languageVersion = JavaLanguageVersion.of(
        rootProject.findProperty('java_version') ?: '25'
    )

    neoForge {
        version = rootProject.findProperty('neo_version') ?: '26.1.2.94'
    }

    sourceSets {
        main {
            groovy {
                srcDirs = ['scripts']
            }
            resources {
                srcDirs = ['.']
                include '*.bundles.toml'
                include 'assets/**'
                include 'data/**'
            }
        }
    }

    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
        maven { url = 'https://maven.latvian.dev/releases' }
    }

    dependencies {
        implementation "org.apache.groovy:groovy:${rootProject.findProperty('groovy_version') ?: '5.0.4'}"

        def modsDir = rootProject.file(rootProject.findProperty('mods_path') ?: 'mods')
        if (modsDir.exists()) {
            implementation fileTree(modsDir) { include '*.jar' }
        }
    }
}
