javadoc {
    options {
        encoding = 'UTF-8'
        memberLevel = JavadocMemberLevel.PROTECTED
        author = false
        version = true
        windowTitle = "FoundryEngine ${mod_version}"
        docTitle = "FoundryEngine ${mod_version}"
        links 'https://docs.oracle.com/en/java/javase/21/docs/api/'
        //stylesheetFile = file("docs/javadoc/custom.css")
    }

    source = sourceSets.main.allJava
    exclude '**/internal/**'

    failOnError = true
}

tasks.register('javadocJar', Jar) {
    description = 'A Javadoc JAR built with the standard Javadoc tool'
    group = "documentation"
    dependsOn javadoc
    from javadoc.destinationDir
    archiveClassifier.set('javadoc')
}

publishMods {
    changelog = "PLACEHOLDER CHANGELOG"
    type = ALPHA
    modLoaders.add("neoforge")

    file = jar.archiveFile
    additionalFiles.from(javadocJar.archiveFile)

    dryRun = true
}

// Publishing configuration
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            artifact javadocJar
        }
    }
    repositories {
        maven {
            name = "Local"
            url = file("${projectDir}/repo").toURI()
        }
    }
}