javadoc {
    options {
        encoding = 'UTF-8'
        memberLevel = JavadocMemberLevel.PROTECTED
        author = false
        version = true
        windowTitle = "FoundryEngine ${mod_version}"
        docTitle = "FoundryEngine ${mod_version}"
        links 'https://docs.oracle.com/en/java/javase/21/docs/api/'
        //stylesheetFile = file("docs/javadoc/custom.css")
    }

    source = sourceSets.main.allJava
    exclude '**/internal/**'

    failOnError = true
}

tasks.register('javadocJar', Jar) {
    description = 'A Javadoc JAR built with the standard Javadoc tool'
    group = "documentation"
    dependsOn javadoc
    from javadoc.destinationDir
    archiveClassifier.set('javadoc')
}

// Publishing configuration
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
            artifact javadocJar
        }
    }
    repositories {
        maven {
            name = "Local"
            url = file("${projectDir}/repo").toURI()
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = "https://maven.pkg.github.com/LuckyMcDev/FoundryEngine"
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}