[[bundles]]
bundleId = "minimal"
version = "0.0.1"
displayName = "Minimal"
displayURL = "https://github.com/Example"
authors = "You"
description = '''This is a bundle, which you can copy and rename all occorrences of "minimal" to your bundles id, and start writing stuff.'''
