modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL = "https://github.com/LuckyMcDev"
#logoFile="toolboxlib.png"
#credits="" #optional
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

#[[accessTransformers]]
#"META-INF/accesstransformer.cfg"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
# reason="..."
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

#[features."${mod_id}"]
#openGLVersion="[4.2,)"
