plugins {
	id 'java-gradle-plugin'
}

gradlePlugin {
	plugins {
		foundryEnginePlugin {
			id = 'de.luckymcdev.foundryengine'
			implementationClass = 'de.luckymcdev.foundryengine.plugin.FoundryEnginePlugin'
		}
	}
}

repositories {
	mavenLocal()
	gradlePluginPortal()
	mavenCentral()
	maven { url = 'https://maven.neoforged.net/releases' }
}

dependencies {
	implementation "net.neoforged:moddev-gradle:2.0.140"
	implementation "me.modmuss50:mod-publish-plugin:1.1.0"
}