import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The site is organized into three sections plus a glossary:
 * - getting-started/   lessons that teach a newcomer by building
 * - guides/            recipes and API lookups (how-to and reference merged)
 * - concepts/          discussions of how the engine works
 */
const sidebars: SidebarsConfig = {
	gettingStartedSidebar: [{type: 'autogenerated', dirName: 'getting-started'}],
	guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
	conceptsSidebar: [{type: 'autogenerated', dirName: 'concepts'}],
};

export default sidebars;
