name: Build Javadoc

on:
  workflow_call:

jobs:
  # We call the common gradle runner here
  generate-docs:
    uses: ./.github/workflows/run-gradle.yml
    with:
      task: "dokkaGenerateJavadoc"
      java-version: "21"

  # We still need a step to upload the specific Javadoc artifact for your deployment
  upload-results:
    needs: generate-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Download Generated Javadoc
        uses: actions/upload-artifact@v7
        with:
          name: javadoc
          path: build/dokka/javadoc